### PR TITLE
fix: A non-numeric value encountered

### PR DESCRIPTION
**Pull request by SaigyoujiYuyuko233**
when I try to parsing a docx file, there are a lot for errors that show up "A non-numeric value encountered in"... so I add a function (intval) to fix that problem~

### CODE REVIEW

**Comment by PhilGale92** [comment]
Ah never had that edge case, nice catch.

**Comment by SaigyoujiYuyuko233** [comment]
Maybe just my document is so speacial...

**Comment by PhilGale92** [comment]
Ok merged, and new release (3.8) that includes your change.

Thanks,

**Comment by SaigyoujiYuyuko233** [comment]
You're welcome~  Thank for this awsome project! It help me a lot!

**Pull request merged**
